---
version: '3.7'

volumes:
  tmp:
    driver: local

services:
  ocis:
    image: owncloud/ocis:latest
    ports:
      - 9200:9200
      - 9140:9140
    expose:
      - 9125 #ldap
      - 9126 #ldaps
    environment:
      - PROXY_TRANSPORT_TLS_CERT=/etc/certs/ocis.localhost.crt
      - PROXY_TRANSPORT_TLS_KEY=/etc/certs/ocis.localhost.key
      - PHOENIX_OIDC_METADATA_URL=https://konnectd:9130/.well-known/openid-configuration
      - PHOENIX_OIDC_AUTHORITY=https://konnectd:9130
      - GRAPH_OIDC_ENDPOINT=https://konnectd:9130
      - REVA_OIDC_ISSUER=https://konnectd:9130
      - REVA_DATAGATEWAY_URL=https://konnectd:9130/data
      - REVA_FRONTEND_URL=https://konnectd:9130
      - REVA_OIDC_INSECURE=true
    volumes:
      - ./ocis/proxy-config.json:/config/proxy-config.json
      - ./ocis/identifier-registration.yml:/config/identifier-registration.yml
      - tmp:/tmp/shared
      - ./certs:/etc/certs

  konnectd:
    image: owncloud/ocis-konnectd:latest
    #command: serve --listen 0.0.0.0:9130 --iss https://ocis:9200 ldap
    #command: --log-level=debug
    ports:
      - 9130:9130
    expose:
      - 9130
      - 9999
    environment:
      - LDAP_URI=ldap://ocis:9125
      - LDAP_BINDDN=cn=konnectd,ou=sysusers,dc=example,dc=org
      - LDAP_BINDPW=konnectd
      - LDAP_BASEDN=ou=users,dc=example,dc=org
      - LDAP_SCOPE=sub
      - LDAP_LOGIN_ATTRIBUTE=cn
      - LDAP_EMAIL_ATTRIBUTE=mail
      - LDAP_NAME_ATTRIBUTE=sn
      - LDAP_UUID_ATTRIBUTE=uid
      - LDAP_UUID_ATTRIBUTE_TYPE=text
      - LDAP_FILTER=(objectClass=posixaccount)
      - KONNECTD_TLS=true
      - KONNECTD_ISS=https://konnectd:9130
      - KONNECTD_INSECURE=true
      - KONNECTD_TRANSPORT_TLS_CERT=/etc/certs/konnectd.localhost.crt
      - KONNECTD_TRANSPORT_TLS_KEY=/etc/certs/konnectd.localhost.key
      - KONNECTD_LOG_LEVEL=debug

    volumes:
      #- ./ocis/identifier-registration.yml:/config/identifier-registration.yaml
      - ./certs:/etc/certs
