
---
version: '3.8'

networks:
  testnet:
    name: testnet

services:
  mq-master:
    container_name: mq-master
    image: ocis/eos-mq
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: mq-master.testnet
    networks:
    - testnet
    volumes:
    - ./config/eos.keytab:/etc/eos.keytab:ro
    - ./config/qdb.keytab:/etc/qdb.keytab:ro
    - ./e/master/log:/var/log/eos
    - ./e/master/config:/var/eos/config
    - ./e/master/md:/var/eos/md
    - ./e/master/ns-queue:/var/eos/ns-queue
    environment:
      EOS_SET_MASTER: 1

  mgm-master:
    container_name: mgm-master
    image: ocis/eos-mgm
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: mgm-master.testnet
    networks:
    - testnet
    volumes:
    - ./config/eos.keytab:/etc/eos.keytab:ro
    - ./config/qdb.keytab:/etc/qdb.keytab:ro
    - ./e/master/log:/var/log/eos
    - ./e/master/config:/var/eos/config
    - ./e/master/md:/var/eos/md
    - ./e/master/ns-queue:/var/eos/ns-queue
    environment:
      EOS_SET_MASTER: 1

  ocis:
    container_name: ocis
    image: ocis/eos-ocis
    tty: true
    privileged: true
    stdin_open: true
    ports: 
      - 9200:9200
    env_file:
      - ./config/eos-docker.env
    hostname: ocis.testnet
    networks:
      - testnet
    volumes:
      - ./config/identifier-registration.yml:/etc/ocis/identifier-registration.yml
    environment: 
      EOS_MGM_URL: "root://mgm-master.testnet:1094"
      KONNECTD_IDENTIFIER_REGISTRATION_CONF: /etc/ocis/identifier-registration.yml
      KONNECTD_ISS: https://@IPADDR@:9200
      KONNECTD_LOG_LEVEL: debug
      KONNECTD_TLS: '0'
      PHOENIX_OIDC_AUTHORITY: https://@IPADDR@:9200
      PHOENIX_OIDC_METADATA_URL: https://@IPADDR@:9200/.well-known/openid-configuration
      PHOENIX_WEB_CONFIG_SERVER: https://@IPADDR@:9200
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      REVA_OIDC_ISSUER: https://@IPADDR@:9200
      OCIS_LOG_LEVEL: debug
      REVA_STORAGE_HOME_DRIVER: eos
      REVA_STORAGE_HOME_MOUNT_ID: 1284d238-aa92-42ce-bdc4-0b0000009158
      REVA_STORAGE_HOME_DATA_DRIVER: eos
      REVA_STORAGE_EOS_MASTER_URL: "root://mgm-master.testnet:1094"
      REVA_STORAGE_EOS_SLAVE_URL: "root://mgm-master.testnet:1094"
      REVA_STORAGE_EOS_NAMESPACE: "/eos/dockertest/reva/users"
      DAV_FILES_NAMESPACE: "/eos/"

  fst:
    container_name: fst
    image: ocis/eos-fst
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: fst.testnet
    networks:
    - testnet
    volumes:
    - ./config/eos.keytab:/etc/eos.keytab:ro
    - ./e/fst/var/log/eos:/var/log/eos
    - ./e/fst/disks:/disks
    environment:
      EOS_MGM_URL: "root://mgm-master.testnet"

  quark-1:
    container_name: quark-1
    image: ocis/eos-qdb
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: quark-1.testnet
    networks:
    - testnet
    volumes:
    - ./config/eos.keytab:/etc/eos.keytab:ro
    - ./config/qdb.keytab:/etc/qdb.keytab:ro
    - ./e/quark1/var/log/eos:/var/log/eos
    - ./e/quark1/var/lib/quarkdb:/var/lib/quarkdb
    environment:
      EOS_QDB_DIR: "/var/lib/quarkdb/eosns"
      EOS_QDB_PORT: "7777"
      EOS_QDB_MODE: "raft"
      EOS_QDB_CLUSTER_ID: "3d659c1a-e70f-43f0-bed4-941a2ca0765b"
      EOS_QDB_NODES: "quark-1.testnet:7777,quark-2.testnet:7777,quark-3.testnet:7777"

  quark-2:
    container_name: quark-2
    image: ocis/eos-qdb
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: quark-2.testnet
    networks:
    - testnet
    volumes:
    - ./config/eos.keytab:/etc/eos.keytab:ro
    - ./config/qdb.keytab:/etc/qdb.keytab:ro
    - ./e/quark2/var/log/eos:/var/log/eos
    - ./e/quark2/var/lib/quarkdb:/var/lib/quarkdb
    environment:
      EOS_QDB_DIR: "/var/lib/quarkdb/eosns"
      EOS_QDB_PORT: "7777"
      EOS_QDB_MODE: "raft"
      EOS_QDB_CLUSTER_ID: "3d659c1a-e70f-43f0-bed4-941a2ca0765b"
      EOS_QDB_NODES: "quark-1.testnet:7777,quark-2.testnet:7777,quark-3.testnet:7777"

  quark-3:
    container_name: quark-3
    image: ocis/eos-qdb
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: quark-3.testnet
    networks:
    - testnet
    volumes:
    - ./config/eos.keytab:/etc/eos.keytab:ro
    - ./config/qdb.keytab:/etc/qdb.keytab:ro
    - ./e/quark3/var/log/eos:/var/log/eos
    - ./e/quark3/var/lib/quarkdb:/var/lib/quarkdb
    environment:
      EOS_QDB_DIR: "/var/lib/quarkdb/eosns"
      EOS_QDB_PORT: "7777"
      EOS_QDB_MODE: "raft"
      EOS_QDB_CLUSTER_ID: "3d659c1a-e70f-43f0-bed4-941a2ca0765b"
      EOS_QDB_NODES: "quark-1.testnet:7777,quark-2.testnet:7777,quark-3.testnet:7777"
